name: 'Setup CSC.exe'
description: 'Uses VSWhere.exe to locate latest CSC & put it into the PATH'
author: 'yoavain'
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'download'
  color: 'purple'
